"""Streamlit UI: a small multi-page analytics dashboard over the churn
model -- an Overview landing page, a per-customer risk explorer with SHAP
factors + a guarded Gemini recommendation + an ROI calculator, a segment
analysis page built on the SQL layer, a model-performance/threshold page,
and a RAG Q&A page over the project's own analysis.

Run locally: `streamlit run src/app.py`
Deploy: push to GitHub, point Streamlit Community Cloud at this file, and
set GEMINI_API_KEY in the app's Secrets -- see README for details.

This file intentionally contains no business logic of its own: it only
loads pre-computed artifacts from models/ (built by train_model.py and
explain.py) and calls into explain.py / genai_advisor.py. That keeps the
UI layer thin and means the exact same scoring/explanation logic is used
whether it's invoked from the CLI or from this app.

Styling note: text generated by Gemini (per-customer explanations, RAG
answers) is only ever rendered through st.write()/st.markdown() WITHOUT
unsafe_allow_html, so it's always markdown-escaped and can't inject raw
HTML/JS into the page. unsafe_allow_html is used only for the card/badge
styling below, and only wraps values we computed ourselves (probabilities,
feature names) or that come from the fixed ALLOWED_ACTIONS / corpus-source
lists -- never free-form model output.

Color discipline: red/amber/green are reserved for risk and ROI signal
only (risk badges, the SHAP increases/decreases-risk split, positive vs.
negative expected value). Every other chart or accent -- the segment
breakdowns, the precision/recall curve, nav/brand elements -- uses the
neutral blue/slate palette defined in the design tokens below, so color
never has to be "read" to understand a non-risk number.
"""

import html
import json

import altair as alt
import joblib
import pandas as pd
import streamlit as st
from sklearn.metrics import f1_score, precision_recall_curve, precision_score, recall_score

from config import (
    ALLOWED_ACTIONS,
    FEATURE_COLUMNS,
    FEATURE_IMPORTANCE_PATH,
    ID_COLUMN,
    METRICS_PATH,
    MODEL_PATH,
    SHAP_VALUES_PATH,
    TEST_FEATURES_PATH,
    TEST_PREDICTIONS_PATH,
)
from explain import get_top_factors
from genai_advisor import generate_customer_explanation
from rag_assistant import answer_question, load_or_build_index
from segments import load_churn_by_country, load_recency_risk_tiers

st.set_page_config(page_title="Churn Predictor & Retention Advisor", layout="wide")

GITHUB_URL = "https://github.com/Daton-Star/churn-predictor-retention-advisor"

NAV_PAGES = ["Overview", "Customer Risk", "Segment Analysis", "Model Insights", "Ask the Analyst"]
NAV_SUBTITLES = {
    "Overview": "A one-screen summary of what this tool does and what it found.",
    "Customer Risk": "Select an at-risk customer to see their SHAP risk factors, a guarded "
    "Gemini recommendation, and the expected ROI of acting on it.",
    "Segment Analysis": "Country and recency-tier breakdowns computed by the SQL layer.",
    "Model Insights": "Precision/recall tradeoff across every decision threshold.",
    "Ask the Analyst": "Free-form Q&A grounded in this project's own analysis (RAG).",
}

# Design tokens: an 8px spacing scale and a small type scale, plus a
# deliberately restrained palette -- deep blue + slate neutrals for
# everything, with red/amber/green held back for risk and ROI signal only
# (see module docstring). Primary blue also matches .streamlit/config.toml.
CUSTOM_CSS = """
<style>
:root {
    --space-1: 4px; --space-2: 8px; --space-3: 12px; --space-4: 16px;
    --space-5: 24px; --space-6: 32px; --space-7: 48px; --space-8: 64px;

    --text-xs: 0.75rem; --text-sm: 0.8125rem; --text-base: 0.875rem;
    --text-md: 1rem; --text-lg: 1.125rem; --text-xl: 1.375rem;
    --text-2xl: 1.75rem; --text-3xl: 2.25rem;

    --color-primary: #1D4ED8;
    --color-primary-dark: #1E3A8A;
    --color-primary-soft: #EFF6FF;
    --color-bg: #FFFFFF;
    --color-surface: #F8FAFC;
    --color-border: #E2E8F0;
    --color-border-hover: #BFDBFE;
    --color-text: #0F172A;
    --color-text-muted: #64748B;
    --color-text-faint: #94A3B8;

    --color-risk-critical-bg: #FEE2E2; --color-risk-critical-fg: #B91C1C;
    --color-risk-high-bg: #FFEDD5;     --color-risk-high-fg: #C2410C;
    --color-risk-elevated-bg: #FEF9C3; --color-risk-elevated-fg: #A16207;
    --color-positive-bg: #DCFCE7; --color-positive-fg: #166534;
    --color-negative-fg: #B91C1C;
}

.block-container { padding-top: var(--space-6); max-width: 1180px; }
h1 { letter-spacing: -0.02em; font-size: var(--text-3xl) !important; }
h3 { font-size: var(--text-xl) !important; }

/* -- Sidebar / product shell -------------------------------------------- */
section[data-testid="stSidebar"] { background: var(--color-surface); border-right: 1px solid var(--color-border); }
.brand-mark { padding: var(--space-2) 0 var(--space-4) 0; }
.brand-eyebrow {
    font-size: var(--text-xs); font-weight: 700; color: var(--color-primary);
    text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: var(--space-1);
}
.brand-name { font-size: var(--text-lg); font-weight: 700; color: var(--color-text); line-height: 1.25; }

/* -- KPI / stat cards ----------------------------------------------------- */
.stat-row { display: flex; gap: var(--space-3); flex-wrap: wrap; margin: var(--space-4) 0 var(--space-6) 0; }
.stat-card {
    flex: 1; min-width: 160px;
    background: var(--color-bg); border: 1px solid var(--color-border); border-top: 3px solid var(--color-primary);
    border-radius: 10px; padding: var(--space-4);
    transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
}
.stat-card:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(15, 23, 42, 0.08); border-color: var(--color-border-hover); }
.stat-label { font-size: var(--text-xs); font-weight: 600; color: var(--color-text-muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: var(--space-1); }
.stat-value { font-size: var(--text-xl); font-weight: 700; color: var(--color-text); }

/* -- Risk badges (the only place red/amber appear outside ROI) ----------- */
.risk-badge { display: inline-block; padding: var(--space-1) var(--space-3); border-radius: 999px; font-weight: 600; font-size: var(--text-sm); }
.risk-critical { background: var(--color-risk-critical-bg); color: var(--color-risk-critical-fg); }
.risk-high     { background: var(--color-risk-high-bg);     color: var(--color-risk-high-fg); }
.risk-elevated { background: var(--color-risk-elevated-bg); color: var(--color-risk-elevated-fg); }

/* -- Risk gauge (pure CSS, no chart lib -- see render_customer_explorer) - */
.gauge-row { display: flex; align-items: center; gap: var(--space-4); flex-wrap: wrap; }
.gauge {
    width: 128px; height: 128px; border-radius: 50%; flex-shrink: 0;
    display: flex; align-items: center; justify-content: center;
    transition: background 0.7s cubic-bezier(0.22, 1, 0.36, 1);
}
.gauge-inner {
    width: 98px; height: 98px; border-radius: 50%; background: var(--color-bg);
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    box-shadow: inset 0 0 0 1px var(--color-surface);
}
.gauge-value { font-size: var(--text-xl); font-weight: 700; color: var(--color-text); line-height: 1.05; }
.gauge-sub { font-size: var(--text-xs); color: var(--color-text-faint); text-transform: uppercase; letter-spacing: 0.04em; margin-top: var(--space-1); }

.mini-stat-row { display: flex; gap: var(--space-2); flex-direction: column; }
.mini-stat {
    background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 8px; padding: var(--space-2) var(--space-4);
    display: flex; align-items: baseline; justify-content: space-between;
    transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
}
.mini-stat:hover { transform: translateX(2px); box-shadow: 0 4px 10px rgba(15, 23, 42, 0.06); border-color: var(--color-border-hover); }
.mini-label { font-size: var(--text-sm); color: var(--color-text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
.mini-value { font-size: var(--text-md); font-weight: 700; color: var(--color-text); }

/* -- Recommendation / RAG answer accents ---------------------------------- */
.action-pill {
    display: inline-block; font-weight: 700; font-size: var(--text-base); color: var(--color-positive-fg);
    background: var(--color-positive-bg); border-radius: 8px; padding: var(--space-1) var(--space-3); margin-bottom: var(--space-2);
}
.source-chip {
    display: inline-block; background: var(--color-primary-soft); color: var(--color-primary); border-radius: 6px;
    padding: 2px var(--space-2); font-size: var(--text-xs); font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    margin: var(--space-1) var(--space-2) var(--space-1) 0;
}
.ev-positive { color: var(--color-positive-fg); }
.ev-negative { color: var(--color-negative-fg); }

/* -- Overview page --------------------------------------------------------- */
.hero {
    background: linear-gradient(135deg, var(--color-primary-soft) 0%, #FFFFFF 100%);
    border: 1px solid var(--color-border); border-radius: 14px;
    padding: var(--space-6); margin-bottom: var(--space-5);
}
.hero-eyebrow { font-size: var(--text-xs); font-weight: 700; color: var(--color-primary); text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: var(--space-2); }
.hero-title { font-size: var(--text-2xl); font-weight: 700; color: var(--color-text); line-height: 1.2; margin-bottom: var(--space-2); }
.hero-body { font-size: var(--text-md); color: var(--color-text-muted); max-width: 640px; line-height: 1.55; }

.nav-card {
    display: block; background: var(--color-bg); border: 1px solid var(--color-border); border-radius: 10px;
    padding: var(--space-4); height: 100%;
    transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
}
.nav-card:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(15, 23, 42, 0.08); border-color: var(--color-border-hover); }
.nav-card-title { font-size: var(--text-md); font-weight: 700; color: var(--color-text); margin-bottom: var(--space-1); }
.nav-card-body { font-size: var(--text-sm); color: var(--color-text-muted); line-height: 1.5; }

/* -- Skeleton loading state (used only for the two real network calls) --- */
@keyframes skeleton-pulse { 0% { opacity: 0.55; } 50% { opacity: 1; } 100% { opacity: 0.55; } }
.skeleton-card { border: 1px solid var(--color-border); border-radius: 10px; padding: var(--space-4); background: var(--color-bg); }
.skeleton-line { height: 12px; border-radius: 6px; background: var(--color-border); margin-bottom: var(--space-3); animation: skeleton-pulse 1.3s ease-in-out infinite; }
.skeleton-line:last-child { margin-bottom: 0; }
.skeleton-w-40 { width: 40%; } .skeleton-w-60 { width: 60%; } .skeleton-w-90 { width: 90%; } .skeleton-w-full { width: 100%; }

div[data-testid="stButton"] button { transition: transform 0.12s ease; }
div[data-testid="stButton"] button:hover { transform: translateY(-1px); }

/* -- Responsive: stack the gauge and tighten padding on small screens ---- */
@media (max-width: 640px) {
    .block-container { padding-top: var(--space-4); padding-left: var(--space-3); padding-right: var(--space-3); }
    .gauge-row { flex-direction: column; align-items: flex-start; }
    .hero { padding: var(--space-4); }
    .hero-title { font-size: var(--text-xl); }
}
</style>
"""

# Illustrative placeholder costs (USD) for each guardrailed retention action --
# not real campaign data (this project has none), just plausible orders of
# magnitude so the ROI calculator below has a sensible starting point. Meant
# to be overridden with a real cost in the number input.
DEFAULT_ACTION_COST = {
    "send discount offer": 15.0,
    "proactive support call": 20.0,
    "loyalty upgrade": 30.0,
    "re-engagement email": 2.0,
    "no action needed": 0.0,
}


def _escape_markdown_dollars(text):
    """Escape literal '$' in LLM-generated text before handing it to
    Streamlit's markdown renderer.

    Gemini's answers often cite dollar figures (e.g. "$3,462,227 in
    revenue"). Streamlit renders markdown through MathJax, which treats a
    matched pair of unescaped '$' as inline LaTeX -- two dollar amounts in
    one sentence get silently parsed as a math expression instead of shown
    as text. Escaping to '\\$' keeps the literal dollar sign without
    triggering math mode.
    """
    return text.replace("$", r"\$") if text else text


def _risk_tier(prob):
    if prob >= 0.9:
        return "Critical risk", "risk-critical", "#DC2626"
    if prob >= 0.75:
        return "High risk", "risk-high", "#EA580C"
    return "Elevated risk", "risk-elevated", "#CA8A04"


def _skeleton(lines=("skeleton-w-40", "skeleton-w-90", "skeleton-w-60")):
    """A small shimmering placeholder shown only while a real network call
    (Gemini) is in flight -- not used anywhere content loads instantly from
    local disk, since a skeleton over instant content is theater, not
    polish."""
    rows = "".join(f'<div class="skeleton-line {cls}"></div>' for cls in lines)
    return f'<div class="skeleton-card">{rows}</div>'


@st.cache_resource
def load_artifacts():
    model_bundle = joblib.load(MODEL_PATH)
    shap_bundle = joblib.load(SHAP_VALUES_PATH)
    predictions = pd.read_csv(TEST_PREDICTIONS_PATH)
    test_features = pd.read_csv(TEST_FEATURES_PATH)
    return model_bundle, shap_bundle, predictions, test_features


@st.cache_resource
def load_metrics():
    with open(METRICS_PATH) as f:
        return json.load(f)


@st.cache_resource
def load_feature_importance():
    with open(FEATURE_IMPORTANCE_PATH) as f:
        return json.load(f)


@st.cache_resource
def load_rag_index():
    # Cached per app process: building the index costs one Gemini API call
    # per corpus chunk (~12), which only needs to happen once whether it's
    # loaded from a locally pre-built models/rag_index.joblib or embedded
    # fresh on first use (e.g. a freshly deployed Streamlit Cloud app).
    return load_or_build_index()


def render_kpi_row(model_bundle, metrics, at_risk_count, total_count):
    st.markdown(
        f"""
        <div class="stat-row">
            <div class="stat-card"><div class="stat-label">Best model</div>
                <div class="stat-value">{html.escape(model_bundle['model_name'].replace('_', ' ').title())}</div></div>
            <div class="stat-card"><div class="stat-label">Test AUC-ROC</div>
                <div class="stat-value">{metrics['test_metrics']['test_roc_auc']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">Test F1</div>
                <div class="stat-value">{metrics['test_metrics']['test_f1']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">At risk (test set)</div>
                <div class="stat-value">{at_risk_count:,} / {total_count:,}</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _go_to(page):
    # Streamlit reruns the script automatically after an on_click callback
    # returns and picks up this session_state change on that rerun -- no
    # explicit st.rerun() here (calling it inside a callback is unsupported).
    st.session_state["nav_page"] = page


def render_overview(metrics, at_risk_count, total_count, feature_importance):
    top_driver = max(feature_importance, key=feature_importance.get).replace("_", " ")
    churn_rate = metrics["churn_rate"]

    st.markdown(
        f"""
        <div class="hero">
            <div class="hero-eyebrow">Retention intelligence</div>
            <div class="hero-title">Know who's about to churn, why, and what it's worth to act.</div>
            <div class="hero-body">
                Trained on {metrics['train_rows'] + metrics['test_rows']:,} real customers from the
                UCI Online Retail II dataset (~1M transaction line items), this tool scores every
                customer's churn risk, explains the top statistical drivers with SHAP, and turns
                that into a guardrailed Gemini recommendation with an expected-value ROI estimate --
                not just a probability.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("##### At a glance")
    render_kpi_row_extended(metrics, at_risk_count, total_count, churn_rate, top_driver)

    st.markdown("##### Explore")
    cards = [
        ("Customer Risk", "Pick an at-risk customer, see their SHAP factors, generate a Gemini recommendation, and estimate its ROI."),
        ("Segment Analysis", "Churn rate by country and revenue by recency-risk tier, computed via SQL."),
        ("Model Insights", "Precision/recall tradeoff across every decision threshold, with a live confusion matrix."),
        ("Ask the Analyst", "Ask a free-form question about this project's own analysis, grounded via retrieval (RAG)."),
    ]
    cols = st.columns(4)
    for col, (name, desc) in zip(cols, cards):
        with col:
            st.markdown(
                f"""
                <div class="nav-card">
                    <div class="nav-card-title">{name}</div>
                    <div class="nav-card-body">{desc}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.button(f"Open {name} →", key=f"go_{name}", use_container_width=True, on_click=_go_to, args=(name,))

    st.caption(
        "This dashboard scores a fixed, pre-trained test set rather than accepting live CSV "
        "uploads -- see the README for how to retrain the pipeline on new data from the CLI."
    )


def render_kpi_row_extended(metrics, at_risk_count, total_count, churn_rate, top_driver):
    st.markdown(
        f"""
        <div class="stat-row">
            <div class="stat-card"><div class="stat-label">Total customers scored</div>
                <div class="stat-value">{total_count:,}</div></div>
            <div class="stat-card"><div class="stat-label">Churn rate</div>
                <div class="stat-value">{churn_rate:.1%}</div></div>
            <div class="stat-card"><div class="stat-label">Test AUC-ROC</div>
                <div class="stat-value">{metrics['test_metrics']['test_roc_auc']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">Top churn driver</div>
                <div class="stat-value" style="font-size: var(--text-base); text-transform: capitalize;">{html.escape(top_driver)}</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_customer_explorer(model_bundle, shap_bundle, predictions, test_features):
    shap_df = shap_bundle["shap_values"]

    at_risk = predictions[predictions["y_pred"] == 1].sort_values("churn_probability", ascending=False)

    if at_risk.empty:
        st.warning("No customers were flagged as at-risk in the test set.")
        st.stop()

    options = [
        f"Customer {row.customer_id}  —  {row.churn_probability:.1%} churn probability"
        for row in at_risk.itertuples()
    ]
    id_lookup = dict(zip(options, at_risk["customer_id"]))

    selected_label = st.selectbox("Select an at-risk customer", options)
    customer_id = id_lookup[selected_label]

    customer_row = predictions[predictions[ID_COLUMN] == customer_id].iloc[0]
    feature_row = test_features[test_features[ID_COLUMN] == customer_id].iloc[0]
    prob = customer_row["churn_probability"]
    tier_label, tier_class, tier_color = _risk_tier(prob)

    col1, col2 = st.columns([1, 1.4])
    with col1:
        # A pure-CSS conic-gradient ring rather than a chart library -- cheap,
        # zero extra rendering risk, and animates smoothly via the .gauge
        # transition when a different customer is selected.
        st.markdown(
            f"""
            <div class="gauge-row">
                <div class="gauge" style="background: conic-gradient({tier_color} 0deg {prob * 360:.1f}deg, #E2E8F0 {prob * 360:.1f}deg 360deg);">
                    <div class="gauge-inner">
                        <div class="gauge-value">{prob:.1%}</div>
                        <div class="gauge-sub">churn risk</div>
                    </div>
                </div>
                <div>
                    <div class="risk-badge {tier_class}">{tier_label}</div>
                    <div style="margin-top: 0.5rem; font-size: var(--text-sm); color: var(--color-text-muted);">Predicted probability this customer stops purchasing.</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with col2:
        st.markdown(
            f"""
            <div class="mini-stat-row">
                <div class="mini-stat"><div class="mini-label">Lifetime orders</div><div class="mini-value">{int(feature_row['frequency']):,}</div></div>
                <div class="mini-stat"><div class="mini-label">Lifetime value</div><div class="mini-value">${feature_row['monetary']:,.0f}</div></div>
                <div class="mini-stat"><div class="mini-label">Tenure</div><div class="mini-value">{int(feature_row['tenure_days']):,}d</div></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # test_features carries the exact feature vector explain.py computed
    # SHAP values against, so the chart shown here matches the model input.
    top_factors = get_top_factors(customer_id, shap_df, test_features[FEATURE_COLUMNS], test_features[ID_COLUMN], top_n=5)

    st.subheader("Top SHAP risk factors")
    st.caption(
        "How much each feature pushed this customer's predicted churn probability up or down, "
        "relative to the model's average prediction."
    )

    # top_factors is already sorted by |impact| descending (see
    # explain.get_top_factors); pin the chart's category order to that same
    # list rather than an in-chart "sort=-x" expression.
    chart_df = top_factors.copy()
    feature_order = chart_df["feature"].tolist()
    chart_df["direction_label"] = chart_df["direction"].map(
        {"increases churn risk": "Increases risk", "decreases churn risk": "Decreases risk"}
    )
    chart = (
        alt.Chart(chart_df)
        .mark_bar(cornerRadiusEnd=4)
        .encode(
            x=alt.X("shap_value:Q", title="Impact on churn probability"),
            y=alt.Y("feature:N", sort=feature_order, title=None, axis=alt.Axis(labelLimit=200)),
            color=alt.Color(
                "direction_label:N",
                title=None,
                scale=alt.Scale(domain=["Increases risk", "Decreases risk"], range=["#DC2626", "#16A34A"]),
                legend=alt.Legend(orient="top", title=None),
            ),
            tooltip=[
                alt.Tooltip("feature:N", title="Feature"),
                alt.Tooltip("value:Q", title="Customer value", format=",.1f"),
                alt.Tooltip("shap_value:Q", title="SHAP impact", format="+.3f"),
            ],
        )
    )
    st.altair_chart(chart, use_container_width=True)

    st.subheader("Gemini retention recommendation")
    if st.button("Generate explanation", type="primary"):
        skeleton_slot = st.empty()
        skeleton_slot.markdown(_skeleton(), unsafe_allow_html=True)
        result = generate_customer_explanation(
            customer_id=customer_id,
            churn_probability=prob,
            top_factors=top_factors.to_dict("records"),
        )
        skeleton_slot.empty()

        if result["needs_manual_review"]:
            with st.container(border=True):
                st.warning(f"Flagged for manual review: {result['error']}")
                if result["explanation"]:
                    st.caption("Model's explanation (unvalidated):")
                    st.write(_escape_markdown_dollars(result["explanation"]))
        else:
            # recommended_action is guaranteed to be an exact match from the
            # fixed ALLOWED_ACTIONS list (see genai_advisor.py's guardrail
            # check) whenever needs_manual_review is False, so it's safe to
            # place directly in this unsafe_allow_html block.
            with st.container(border=True):
                st.markdown(f'<div class="action-pill">{result["recommended_action"]}</div>', unsafe_allow_html=True)
                st.write(_escape_markdown_dollars(result["explanation"]))
            st.balloons()

    st.subheader("Estimated ROI of intervening")
    st.caption(
        "A simplified expected-value model: "
        "**effectiveness x churn probability x lifetime value − cost**. "
        "Effectiveness (how often this action actually retains an at-risk customer) isn't "
        "something this project has real data for -- adjust the slider to your own campaign "
        "numbers; lifetime value uses this customer's historical spend as a proxy for future value."
    )
    roi_col1, roi_col2 = st.columns(2)
    with roi_col1:
        action = st.selectbox("Retention action", ALLOWED_ACTIONS, key="roi_action")
        cost = st.number_input(
            "Cost of this action ($)",
            min_value=0.0,
            value=DEFAULT_ACTION_COST[action],
            step=1.0,
            key="roi_cost",
        )
    with roi_col2:
        effectiveness_pct = st.slider(
            "Assumed effectiveness (% of at-risk customers this action retains)",
            min_value=0,
            max_value=100,
            value=20,
            step=5,
            key="roi_effectiveness",
        )
        expected_value = (effectiveness_pct / 100) * prob * feature_row["monetary"] - cost
        ev_class = "ev-positive" if expected_value >= 0 else "ev-negative"
        sign = "+" if expected_value >= 0 else "−"
        st.markdown(
            f'<div class="mini-label">Expected value of intervening</div>'
            f'<div class="stat-value {ev_class}" style="font-size: var(--text-2xl);">{sign}${abs(expected_value):,.2f}</div>',
            unsafe_allow_html=True,
        )


def render_segment_analysis():
    st.caption(
        "Computed via SQL against the same cleaned dataset the model trains on -- see "
        "`sql/` for the queries and `sql/QUERY_RESULTS.md` for the full committed output. "
        "Bars use the neutral brand blue throughout: color here encodes nothing but magnitude, "
        "so it's never confused with the risk-severity colors used elsewhere in this app."
    )

    st.subheader("Churn rate by country")
    st.caption("Countries with at least 20 customers, so the rate is statistically meaningful.")
    country_df = load_churn_by_country()
    country_chart = (
        alt.Chart(country_df)
        .mark_bar(cornerRadiusEnd=4, color="#1D4ED8")
        .encode(
            x=alt.X("churn_rate_pct:Q", title="Churn rate (%)"),
            y=alt.Y("country:N", sort="-x", title=None),
            tooltip=[
                alt.Tooltip("country:N", title="Country"),
                alt.Tooltip("num_customers:Q", title="Customers"),
                alt.Tooltip("churn_rate_pct:Q", title="Churn rate (%)"),
                alt.Tooltip("total_revenue:Q", title="Total revenue", format=",.0f"),
            ],
        )
    )
    st.altair_chart(country_chart, use_container_width=True)

    st.subheader("Revenue by recency-risk tier")
    st.caption("A simple 'traffic light' segmentation a retention team can act on directly.")
    tier_df = load_recency_risk_tiers()
    tier_chart = (
        alt.Chart(tier_df)
        .mark_bar(cornerRadiusEnd=4, color="#1D4ED8")
        .encode(
            x=alt.X("total_revenue:Q", title="Total revenue ($)"),
            y=alt.Y("risk_tier:N", sort=None, title=None),
            tooltip=[
                alt.Tooltip("risk_tier:N", title="Tier"),
                alt.Tooltip("num_customers:Q", title="Customers"),
                alt.Tooltip("avg_customer_value:Q", title="Avg. customer value", format=",.0f"),
                alt.Tooltip("total_revenue:Q", title="Total revenue", format=",.0f"),
            ],
        )
    )
    st.altair_chart(tier_chart, use_container_width=True)


def render_model_performance(predictions):
    st.caption(
        "The app flags a customer as 'at risk' above a 0.5 churn-probability threshold by "
        "default. That threshold is a business decision, not a statistical fact -- raising it "
        "trades recall for precision (fewer false alarms, but more missed at-risk customers) "
        "and vice versa. Explore that tradeoff here."
    )

    y_true = predictions["y_true"].to_numpy()
    y_prob = predictions["churn_probability"].to_numpy()

    precision_vals, recall_vals, thresholds = precision_recall_curve(y_true, y_prob)
    curve_df = pd.concat(
        [
            pd.DataFrame({"threshold": thresholds, "value": precision_vals[:-1], "metric": "Precision"}),
            pd.DataFrame({"threshold": thresholds, "value": recall_vals[:-1], "metric": "Recall"}),
        ]
    )
    curve_chart = (
        alt.Chart(curve_df)
        .mark_line()
        .encode(
            x=alt.X("threshold:Q", title="Decision threshold"),
            y=alt.Y("value:Q", title="Score", scale=alt.Scale(domain=[0, 1])),
            color=alt.Color(
                "metric:N",
                title=None,
                # Blue + slate, not orange: this is a generic two-series
                # comparison, not a risk signal, so it stays inside the
                # neutral palette rather than borrowing an amber/red tone.
                scale=alt.Scale(domain=["Precision", "Recall"], range=["#1D4ED8", "#475569"]),
                legend=alt.Legend(orient="top", title=None),
            ),
        )
    )
    st.altair_chart(curve_chart, use_container_width=True)

    threshold = st.slider(
        "Pick a decision threshold to inspect",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01,
        key="perf_threshold",
    )
    y_pred_at_threshold = (y_prob >= threshold).astype(int)
    tn = int(((y_true == 0) & (y_pred_at_threshold == 0)).sum())
    fp = int(((y_true == 0) & (y_pred_at_threshold == 1)).sum())
    fn = int(((y_true == 1) & (y_pred_at_threshold == 0)).sum())
    tp = int(((y_true == 1) & (y_pred_at_threshold == 1)).sum())

    metric_col1, metric_col2, metric_col3 = st.columns(3)
    metric_col1.metric("Precision", f"{precision_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")
    metric_col2.metric("Recall", f"{recall_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")
    metric_col3.metric("F1", f"{f1_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")

    confusion_df = pd.DataFrame(
        {
            "": ["Actual: not churned", "Actual: churned"],
            "Predicted: not at risk": [tn, fn],
            "Predicted: at risk": [fp, tp],
        }
    )
    st.dataframe(confusion_df, use_container_width=True, hide_index=True)


EXAMPLE_QUESTIONS = [
    "Which customer segment has the highest churn risk and why?",
    "How much revenue is sitting with customers who have already churned?",
    "What did the RFM feature engineering exclude, and why?",
    "Which model performed best and by how much?",
]


def render_ask_the_analysis():
    st.caption(
        "Ask a free-form question about this project's own analysis. The assistant retrieves "
        "the most relevant snippets from the SQL results, model metrics, SHAP importances, and "
        "README findings, then answers using only those snippets -- see src/rag_assistant.py "
        "for the retrieval + guardrail design."
    )

    if "rag_question" not in st.session_state:
        st.session_state["rag_question"] = ""

    st.caption("Try one:")
    chip_cols = st.columns(len(EXAMPLE_QUESTIONS))
    for col, q in zip(chip_cols, EXAMPLE_QUESTIONS):
        if col.button(q, key=f"chip_{q}", use_container_width=True):
            st.session_state["rag_question"] = q

    question = st.text_input("Your question", key="rag_question", placeholder=EXAMPLE_QUESTIONS[0])

    if st.button("Ask", type="primary") and question.strip():
        skeleton_slot = st.empty()
        skeleton_slot.markdown(_skeleton(), unsafe_allow_html=True)
        try:
            index = load_rag_index()
            result = answer_question(question, index=index)
        except Exception as exc:  # noqa: BLE001 - index build can fail without a valid key
            result = {"answer": None, "sources": [], "error": f"Could not build/load the RAG index: {exc}"}
        skeleton_slot.empty()

        if result["error"]:
            st.warning(result["error"])
        else:
            with st.container(border=True):
                st.write(_escape_markdown_dollars(result["answer"]))
                if result["sources"]:
                    # Source keys come from our own indexed corpus (file
                    # names / chunk labels defined in rag_assistant.py), not
                    # from the model, but they're escaped anyway as cheap
                    # defense-in-depth before going into unsafe_allow_html.
                    chips = "".join(f'<span class="source-chip">{html.escape(s)}</span>' for s in result["sources"])
                    st.markdown(f'<div style="margin-top:0.5rem;">{chips}</div>', unsafe_allow_html=True)


def main():
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

    try:
        model_bundle, shap_bundle, predictions, test_features = load_artifacts()
        metrics = load_metrics()
        feature_importance = load_feature_importance()
    except FileNotFoundError:
        st.error(
            "Model artifacts not found. Run the pipeline first:\n\n"
            "`python src/data_prep.py && python src/train_model.py && python src/explain.py`"
        )
        st.stop()

    at_risk = predictions[predictions["y_pred"] == 1]
    at_risk_count, total_count = len(at_risk), len(predictions)

    if "nav_page" not in st.session_state:
        st.session_state["nav_page"] = "Overview"

    with st.sidebar:
        st.markdown(
            """
            <div class="brand-mark">
                <div class="brand-eyebrow">Churn Intelligence</div>
                <div class="brand-name">Retention Advisor</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        page = st.radio("Navigate", NAV_PAGES, key="nav_page", label_visibility="collapsed")
        st.divider()
        st.caption(
            "An end-to-end churn prediction system: RFM-based churn labels, a "
            "leakage-checked model comparison, SHAP explainability, and a "
            "guardrailed Gemini retention advisor."
        )
        st.markdown(f"[Source on GitHub]({GITHUB_URL})")
        st.markdown("[Full methodology (README)](%s#readme)" % GITHUB_URL)

    st.title("Intelligent Churn Predictor & Retention Advisor")
    st.caption(NAV_SUBTITLES[page])

    if page != "Overview":
        render_kpi_row(model_bundle, metrics, at_risk_count, total_count)

    if page == "Overview":
        render_overview(metrics, at_risk_count, total_count, feature_importance)
    elif page == "Customer Risk":
        render_customer_explorer(model_bundle, shap_bundle, predictions, test_features)
    elif page == "Segment Analysis":
        render_segment_analysis()
    elif page == "Model Insights":
        render_model_performance(predictions)
    elif page == "Ask the Analyst":
        render_ask_the_analysis()


if __name__ == "__main__":
    main()
