"""Streamlit UI: pick an at-risk customer, see their SHAP risk factors, and
generate an on-demand plain-English explanation + guarded retention action
from Gemini.

Run locally: `streamlit run src/app.py`
Deploy: push to GitHub, point Streamlit Community Cloud at this file, and
set GEMINI_API_KEY in the app's Secrets -- see README for details.

This file intentionally contains no business logic of its own: it only
loads pre-computed artifacts from models/ (built by train_model.py and
explain.py) and calls into explain.py / genai_advisor.py. That keeps the
UI layer thin and means the exact same scoring/explanation logic is used
whether it's invoked from the CLI or from this app.

Styling note: text generated by Gemini (per-customer explanations, RAG
answers) is only ever rendered through st.write()/st.markdown() WITHOUT
unsafe_allow_html, so it's always markdown-escaped and can't inject raw
HTML/JS into the page. unsafe_allow_html is used only for the card/badge
styling below, and only wraps values we computed ourselves (probabilities,
feature names) or that come from the fixed ALLOWED_ACTIONS / corpus-source
lists -- never free-form model output.
"""

import html
import json

import altair as alt
import joblib
import pandas as pd
import streamlit as st
from sklearn.metrics import f1_score, precision_recall_curve, precision_score, recall_score

from config import (
    ALLOWED_ACTIONS,
    FEATURE_COLUMNS,
    ID_COLUMN,
    METRICS_PATH,
    MODEL_PATH,
    SHAP_VALUES_PATH,
    TEST_FEATURES_PATH,
    TEST_PREDICTIONS_PATH,
)
from explain import get_top_factors
from genai_advisor import generate_customer_explanation
from rag_assistant import answer_question, load_or_build_index
from segments import load_churn_by_country, load_recency_risk_tiers

st.set_page_config(page_title="Churn Predictor & Retention Advisor", layout="wide")

CUSTOM_CSS = """
<style>
.block-container { padding-top: 2.2rem; max-width: 1180px; }
h1 { letter-spacing: -0.02em; }

.stat-row { display: flex; gap: 0.9rem; flex-wrap: wrap; margin: 1rem 0 1.6rem 0; }
.stat-card {
    flex: 1; min-width: 160px;
    background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px;
    padding: 0.85rem 1.1rem;
    transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
}
.stat-card:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(15, 23, 42, 0.08); border-color: #C7D2FE; }
.stat-label { font-size: 0.72rem; font-weight: 600; color: #64748B; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.3rem; }
.stat-value { font-size: 1.4rem; font-weight: 700; color: #0F172A; }

.risk-badge { display: inline-block; padding: 0.28rem 0.8rem; border-radius: 999px; font-weight: 600; font-size: 0.8rem; }
.risk-critical { background: #FEE2E2; color: #B91C1C; }
.risk-high     { background: #FFEDD5; color: #C2410C; }
.risk-elevated { background: #FEF9C3; color: #A16207; }

.prob-value { font-size: 2.1rem; font-weight: 700; color: #0F172A; line-height: 1.1; }
.prob-track { background: #E2E8F0; border-radius: 999px; height: 9px; width: 100%; overflow: hidden; margin-top: 0.5rem; }
.prob-fill { height: 100%; border-radius: 999px; transition: width 0.7s cubic-bezier(0.22, 1, 0.36, 1); }

.gauge-row { display: flex; align-items: center; gap: 1.1rem; }
.gauge {
    width: 128px; height: 128px; border-radius: 50%; flex-shrink: 0;
    display: flex; align-items: center; justify-content: center;
    transition: background 0.7s cubic-bezier(0.22, 1, 0.36, 1);
}
.gauge-inner {
    width: 98px; height: 98px; border-radius: 50%; background: #FFFFFF;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    box-shadow: inset 0 0 0 1px #F1F5F9;
}
.gauge-value { font-size: 1.55rem; font-weight: 700; color: #0F172A; line-height: 1.05; }
.gauge-sub { font-size: 0.62rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.04em; margin-top: 0.15rem; }

.mini-stat-row { display: flex; gap: 0.7rem; flex-direction: column; }
.mini-stat {
    background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 10px; padding: 0.55rem 0.9rem;
    display: flex; align-items: baseline; justify-content: space-between;
    transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
}
.mini-stat:hover { transform: translateX(2px); box-shadow: 0 4px 10px rgba(15, 23, 42, 0.06); border-color: #C7D2FE; }
.mini-label { font-size: 0.72rem; color: #64748B; text-transform: uppercase; letter-spacing: 0.04em; }
.mini-value { font-size: 1.05rem; font-weight: 700; color: #0F172A; }

.action-pill {
    display: inline-block; font-weight: 700; font-size: 0.9rem; color: #166534;
    background: #DCFCE7; border-radius: 8px; padding: 0.3rem 0.75rem; margin-bottom: 0.6rem;
}
.source-chip {
    display: inline-block; background: #EEF2FF; color: #4338CA; border-radius: 6px;
    padding: 0.18rem 0.6rem; font-size: 0.74rem; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    margin: 0.2rem 0.35rem 0.2rem 0;
}

.ev-positive { color: #166534; }
.ev-negative { color: #B91C1C; }

/* nudge the "try a question" chip buttons in the RAG tab to look like pills, not full buttons */
div[data-testid="stButton"] button {
    transition: transform 0.12s ease;
}
div[data-testid="stButton"] button:hover { transform: translateY(-1px); }
</style>
"""

# Illustrative placeholder costs (USD) for each guardrailed retention action --
# not real campaign data (this project has none), just plausible orders of
# magnitude so the ROI calculator below has a sensible starting point. Meant
# to be overridden with a real cost in the number input.
DEFAULT_ACTION_COST = {
    "send discount offer": 15.0,
    "proactive support call": 20.0,
    "loyalty upgrade": 30.0,
    "re-engagement email": 2.0,
    "no action needed": 0.0,
}


def _escape_markdown_dollars(text):
    """Escape literal '$' in LLM-generated text before handing it to
    Streamlit's markdown renderer.

    Gemini's answers often cite dollar figures (e.g. "$3,462,227 in
    revenue"). Streamlit renders markdown through MathJax, which treats a
    matched pair of unescaped '$' as inline LaTeX -- two dollar amounts in
    one sentence get silently parsed as a math expression instead of shown
    as text. Escaping to '\\$' keeps the literal dollar sign without
    triggering math mode.
    """
    return text.replace("$", r"\$") if text else text


def _risk_tier(prob):
    if prob >= 0.9:
        return "Critical risk", "risk-critical", "#DC2626"
    if prob >= 0.75:
        return "High risk", "risk-high", "#EA580C"
    return "Elevated risk", "risk-elevated", "#CA8A04"


@st.cache_resource
def load_artifacts():
    model_bundle = joblib.load(MODEL_PATH)
    shap_bundle = joblib.load(SHAP_VALUES_PATH)
    predictions = pd.read_csv(TEST_PREDICTIONS_PATH)
    test_features = pd.read_csv(TEST_FEATURES_PATH)
    return model_bundle, shap_bundle, predictions, test_features


@st.cache_resource
def load_metrics():
    with open(METRICS_PATH) as f:
        return json.load(f)


@st.cache_resource
def load_rag_index():
    # Cached per app process: building the index costs one Gemini API call
    # per corpus chunk (~12), which only needs to happen once whether it's
    # loaded from a locally pre-built models/rag_index.joblib or embedded
    # fresh on first use (e.g. a freshly deployed Streamlit Cloud app).
    return load_or_build_index()


def render_kpi_row(model_bundle, metrics, at_risk_count, total_count):
    st.markdown(
        f"""
        <div class="stat-row">
            <div class="stat-card"><div class="stat-label">Best model</div>
                <div class="stat-value">{html.escape(model_bundle['model_name'].replace('_', ' ').title())}</div></div>
            <div class="stat-card"><div class="stat-label">Test AUC-ROC</div>
                <div class="stat-value">{metrics['test_metrics']['test_roc_auc']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">Test F1</div>
                <div class="stat-value">{metrics['test_metrics']['test_f1']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">At risk (test set)</div>
                <div class="stat-value">{at_risk_count:,} / {total_count:,}</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_customer_explorer(model_bundle, shap_bundle, predictions, test_features):
    shap_df = shap_bundle["shap_values"]

    at_risk = predictions[predictions["y_pred"] == 1].sort_values("churn_probability", ascending=False)

    if at_risk.empty:
        st.warning("No customers were flagged as at-risk in the test set.")
        st.stop()

    options = [
        f"Customer {row.customer_id}  —  {row.churn_probability:.0%} churn probability"
        for row in at_risk.itertuples()
    ]
    id_lookup = dict(zip(options, at_risk["customer_id"]))

    selected_label = st.selectbox("Select an at-risk customer", options)
    customer_id = id_lookup[selected_label]

    customer_row = predictions[predictions[ID_COLUMN] == customer_id].iloc[0]
    feature_row = test_features[test_features[ID_COLUMN] == customer_id].iloc[0]
    prob = customer_row["churn_probability"]
    tier_label, tier_class, tier_color = _risk_tier(prob)

    col1, col2 = st.columns([1, 1.4])
    with col1:
        # A pure-CSS conic-gradient ring rather than a chart library -- cheap,
        # zero extra rendering risk, and animates smoothly via the .gauge
        # transition when a different customer is selected.
        st.markdown(
            f"""
            <div class="gauge-row">
                <div class="gauge" style="background: conic-gradient({tier_color} 0deg {prob * 360:.1f}deg, #E2E8F0 {prob * 360:.1f}deg 360deg);">
                    <div class="gauge-inner">
                        <div class="gauge-value">{prob:.1%}</div>
                        <div class="gauge-sub">churn risk</div>
                    </div>
                </div>
                <div>
                    <div class="risk-badge {tier_class}">{tier_label}</div>
                    <div style="margin-top: 0.5rem; font-size: 0.82rem; color: #64748B;">Predicted probability this customer stops purchasing.</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with col2:
        st.markdown(
            f"""
            <div class="mini-stat-row">
                <div class="mini-stat"><div class="mini-label">Lifetime orders</div><div class="mini-value">{int(feature_row['frequency']):,}</div></div>
                <div class="mini-stat"><div class="mini-label">Lifetime value</div><div class="mini-value">${feature_row['monetary']:,.0f}</div></div>
                <div class="mini-stat"><div class="mini-label">Tenure</div><div class="mini-value">{int(feature_row['tenure_days']):,}d</div></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # test_features carries the exact feature vector explain.py computed
    # SHAP values against, so the chart shown here matches the model input.
    top_factors = get_top_factors(customer_id, shap_df, test_features[FEATURE_COLUMNS], test_features[ID_COLUMN], top_n=5)

    st.subheader("Top SHAP risk factors")
    st.caption(
        "How much each feature pushed this customer's predicted churn probability up or down, "
        "relative to the model's average prediction."
    )

    # top_factors is already sorted by |impact| descending (see
    # explain.get_top_factors); pin the chart's category order to that same
    # list rather than an in-chart "sort=-x" expression.
    chart_df = top_factors.copy()
    feature_order = chart_df["feature"].tolist()
    chart_df["direction_label"] = chart_df["direction"].map(
        {"increases churn risk": "Increases risk", "decreases churn risk": "Decreases risk"}
    )
    chart = (
        alt.Chart(chart_df)
        .mark_bar(cornerRadiusEnd=4)
        .encode(
            x=alt.X("shap_value:Q", title="Impact on churn probability"),
            y=alt.Y("feature:N", sort=feature_order, title=None, axis=alt.Axis(labelLimit=200)),
            color=alt.Color(
                "direction_label:N",
                title=None,
                scale=alt.Scale(domain=["Increases risk", "Decreases risk"], range=["#DC2626", "#16A34A"]),
                legend=alt.Legend(orient="top", title=None),
            ),
            tooltip=[
                alt.Tooltip("feature:N", title="Feature"),
                alt.Tooltip("value:Q", title="Customer value", format=",.1f"),
                alt.Tooltip("shap_value:Q", title="SHAP impact", format="+.3f"),
            ],
        )
    )
    st.altair_chart(chart, use_container_width=True)

    st.subheader("Gemini retention recommendation")
    if st.button("Generate explanation", type="primary"):
        with st.spinner("Calling Gemini..."):
            result = generate_customer_explanation(
                customer_id=customer_id,
                churn_probability=prob,
                top_factors=top_factors.to_dict("records"),
            )

        if result["needs_manual_review"]:
            with st.container(border=True):
                st.warning(f"Flagged for manual review: {result['error']}")
                if result["explanation"]:
                    st.caption("Model's explanation (unvalidated):")
                    st.write(_escape_markdown_dollars(result["explanation"]))
        else:
            # recommended_action is guaranteed to be an exact match from the
            # fixed ALLOWED_ACTIONS list (see genai_advisor.py's guardrail
            # check) whenever needs_manual_review is False, so it's safe to
            # place directly in this unsafe_allow_html block.
            with st.container(border=True):
                st.markdown(f'<div class="action-pill">{result["recommended_action"]}</div>', unsafe_allow_html=True)
                st.write(_escape_markdown_dollars(result["explanation"]))
            st.balloons()

    st.subheader("Estimated ROI of intervening")
    st.caption(
        "A simplified expected-value model: "
        "**effectiveness x churn probability x lifetime value − cost**. "
        "Effectiveness (how often this action actually retains an at-risk customer) isn't "
        "something this project has real data for -- adjust the slider to your own campaign "
        "numbers; lifetime value uses this customer's historical spend as a proxy for future value."
    )
    roi_col1, roi_col2 = st.columns(2)
    with roi_col1:
        action = st.selectbox("Retention action", ALLOWED_ACTIONS, key="roi_action")
        cost = st.number_input(
            "Cost of this action ($)",
            min_value=0.0,
            value=DEFAULT_ACTION_COST[action],
            step=1.0,
            key="roi_cost",
        )
    with roi_col2:
        effectiveness_pct = st.slider(
            "Assumed effectiveness (% of at-risk customers this action retains)",
            min_value=0,
            max_value=100,
            value=20,
            step=5,
            key="roi_effectiveness",
        )
        expected_value = (effectiveness_pct / 100) * prob * feature_row["monetary"] - cost
        ev_class = "ev-positive" if expected_value >= 0 else "ev-negative"
        sign = "+" if expected_value >= 0 else "−"
        st.markdown(
            f'<div class="mini-label">Expected value of intervening</div>'
            f'<div class="prob-value {ev_class}">{sign}${abs(expected_value):,.2f}</div>',
            unsafe_allow_html=True,
        )


def render_segment_analysis():
    st.caption(
        "Computed via SQL against the same cleaned dataset the model trains on -- see "
        "`sql/` for the queries and `sql/QUERY_RESULTS.md` for the full committed output."
    )

    st.subheader("Churn rate by country")
    st.caption("Countries with at least 20 customers, so the rate is statistically meaningful.")
    country_df = load_churn_by_country()
    country_chart = (
        alt.Chart(country_df)
        .mark_bar(cornerRadiusEnd=4, color="#4338CA")
        .encode(
            x=alt.X("churn_rate_pct:Q", title="Churn rate (%)"),
            y=alt.Y("country:N", sort="-x", title=None),
            tooltip=[
                alt.Tooltip("country:N", title="Country"),
                alt.Tooltip("num_customers:Q", title="Customers"),
                alt.Tooltip("churn_rate_pct:Q", title="Churn rate (%)"),
                alt.Tooltip("total_revenue:Q", title="Total revenue", format=",.0f"),
            ],
        )
    )
    st.altair_chart(country_chart, use_container_width=True)

    st.subheader("Revenue by recency-risk tier")
    st.caption("A simple 'traffic light' segmentation a retention team can act on directly.")
    tier_df = load_recency_risk_tiers()
    tier_chart = (
        alt.Chart(tier_df)
        .mark_bar(cornerRadiusEnd=4, color="#16A34A")
        .encode(
            x=alt.X("total_revenue:Q", title="Total revenue ($)"),
            y=alt.Y("risk_tier:N", sort=None, title=None),
            tooltip=[
                alt.Tooltip("risk_tier:N", title="Tier"),
                alt.Tooltip("num_customers:Q", title="Customers"),
                alt.Tooltip("avg_customer_value:Q", title="Avg. customer value", format=",.0f"),
                alt.Tooltip("total_revenue:Q", title="Total revenue", format=",.0f"),
            ],
        )
    )
    st.altair_chart(tier_chart, use_container_width=True)


def render_model_performance(predictions):
    st.caption(
        "The app flags a customer as 'at risk' above a 0.5 churn-probability threshold by "
        "default. That threshold is a business decision, not a statistical fact -- raising it "
        "trades recall for precision (fewer false alarms, but more missed at-risk customers) "
        "and vice versa. Explore that tradeoff here."
    )

    y_true = predictions["y_true"].to_numpy()
    y_prob = predictions["churn_probability"].to_numpy()

    precision_vals, recall_vals, thresholds = precision_recall_curve(y_true, y_prob)
    curve_df = pd.concat(
        [
            pd.DataFrame({"threshold": thresholds, "value": precision_vals[:-1], "metric": "Precision"}),
            pd.DataFrame({"threshold": thresholds, "value": recall_vals[:-1], "metric": "Recall"}),
        ]
    )
    curve_chart = (
        alt.Chart(curve_df)
        .mark_line()
        .encode(
            x=alt.X("threshold:Q", title="Decision threshold"),
            y=alt.Y("value:Q", title="Score", scale=alt.Scale(domain=[0, 1])),
            color=alt.Color(
                "metric:N",
                title=None,
                scale=alt.Scale(domain=["Precision", "Recall"], range=["#4338CA", "#EA580C"]),
                legend=alt.Legend(orient="top", title=None),
            ),
        )
    )
    st.altair_chart(curve_chart, use_container_width=True)

    threshold = st.slider(
        "Pick a decision threshold to inspect",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01,
        key="perf_threshold",
    )
    y_pred_at_threshold = (y_prob >= threshold).astype(int)
    tn = int(((y_true == 0) & (y_pred_at_threshold == 0)).sum())
    fp = int(((y_true == 0) & (y_pred_at_threshold == 1)).sum())
    fn = int(((y_true == 1) & (y_pred_at_threshold == 0)).sum())
    tp = int(((y_true == 1) & (y_pred_at_threshold == 1)).sum())

    metric_col1, metric_col2, metric_col3 = st.columns(3)
    metric_col1.metric("Precision", f"{precision_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")
    metric_col2.metric("Recall", f"{recall_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")
    metric_col3.metric("F1", f"{f1_score(y_true, y_pred_at_threshold, zero_division=0):.3f}")

    confusion_df = pd.DataFrame(
        {
            "": ["Actual: not churned", "Actual: churned"],
            "Predicted: not at risk": [tn, fn],
            "Predicted: at risk": [fp, tp],
        }
    )
    st.dataframe(confusion_df, use_container_width=True, hide_index=True)


EXAMPLE_QUESTIONS = [
    "Which customer segment has the highest churn risk and why?",
    "How much revenue is sitting with customers who have already churned?",
    "What did the RFM feature engineering exclude, and why?",
    "Which model performed best and by how much?",
]


def render_ask_the_analysis():
    st.caption(
        "Ask a free-form question about this project's own analysis. The assistant retrieves "
        "the most relevant snippets from the SQL results, model metrics, SHAP importances, and "
        "README findings, then answers using only those snippets -- see src/rag_assistant.py "
        "for the retrieval + guardrail design."
    )

    if "rag_question" not in st.session_state:
        st.session_state["rag_question"] = ""

    st.caption("Try one:")
    chip_cols = st.columns(len(EXAMPLE_QUESTIONS))
    for col, q in zip(chip_cols, EXAMPLE_QUESTIONS):
        if col.button(q, key=f"chip_{q}", use_container_width=True):
            st.session_state["rag_question"] = q

    question = st.text_input("Your question", key="rag_question", placeholder=EXAMPLE_QUESTIONS[0])

    if st.button("Ask", type="primary") and question.strip():
        with st.spinner("Retrieving context and calling Gemini..."):
            try:
                index = load_rag_index()
                result = answer_question(question, index=index)
            except Exception as exc:  # noqa: BLE001 - index build can fail without a valid key
                result = {"answer": None, "sources": [], "error": f"Could not build/load the RAG index: {exc}"}

        if result["error"]:
            st.warning(result["error"])
        else:
            with st.container(border=True):
                st.write(_escape_markdown_dollars(result["answer"]))
                if result["sources"]:
                    # Source keys come from our own indexed corpus (file
                    # names / chunk labels defined in rag_assistant.py), not
                    # from the model, but they're escaped anyway as cheap
                    # defense-in-depth before going into unsafe_allow_html.
                    chips = "".join(f'<span class="source-chip">{html.escape(s)}</span>' for s in result["sources"])
                    st.markdown(f'<div style="margin-top:0.5rem;">{chips}</div>', unsafe_allow_html=True)


def main():
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

    st.title("Intelligent Churn Predictor & Retention Advisor")
    st.caption(
        "Trained on the UCI Online Retail II dataset. Select an at-risk customer to see "
        "the statistical factors driving their churn score, then generate a plain-English "
        "explanation and a guarded retention recommendation with Gemini."
    )

    try:
        model_bundle, shap_bundle, predictions, test_features = load_artifacts()
        metrics = load_metrics()
    except FileNotFoundError:
        st.error(
            "Model artifacts not found. Run the pipeline first:\n\n"
            "`python src/data_prep.py && python src/train_model.py && python src/explain.py`"
        )
        st.stop()

    at_risk = predictions[predictions["y_pred"] == 1]
    render_kpi_row(model_bundle, metrics, len(at_risk), len(predictions))

    st.sidebar.header("About this project")
    st.sidebar.write(
        "An end-to-end churn prediction system: RFM-based churn labels, a "
        "leakage-checked model comparison, SHAP explainability, and a "
        "guardrailed Gemini retention advisor. See the README for the full "
        "methodology and business case."
    )
    st.sidebar.markdown("[Source on GitHub](https://github.com/Daton-Star/churn-predictor-retention-advisor)")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Customer risk explorer", "Segment analysis", "Model performance", "Ask the analysis"]
    )
    with tab1:
        render_customer_explorer(model_bundle, shap_bundle, predictions, test_features)
    with tab2:
        render_segment_analysis()
    with tab3:
        render_model_performance(predictions)
    with tab4:
        render_ask_the_analysis()


if __name__ == "__main__":
    main()
