"""Streamlit UI: pick an at-risk customer, see their SHAP risk factors, and
generate an on-demand plain-English explanation + guarded retention action
from Gemini.

Run locally: `streamlit run src/app.py`
Deploy: push to GitHub, point Streamlit Community Cloud at this file, and
set GEMINI_API_KEY in the app's Secrets -- see README for details.

This file intentionally contains no business logic of its own: it only
loads pre-computed artifacts from models/ (built by train_model.py and
explain.py) and calls into explain.py / genai_advisor.py. That keeps the
UI layer thin and means the exact same scoring/explanation logic is used
whether it's invoked from the CLI or from this app.

Styling note: text generated by Gemini (per-customer explanations, RAG
answers) is only ever rendered through st.write()/st.markdown() WITHOUT
unsafe_allow_html, so it's always markdown-escaped and can't inject raw
HTML/JS into the page. unsafe_allow_html is used only for the card/badge
styling below, and only wraps values we computed ourselves (probabilities,
feature names) or that come from the fixed ALLOWED_ACTIONS / corpus-source
lists -- never free-form model output.
"""

import html
import json

import altair as alt
import joblib
import pandas as pd
import streamlit as st

from config import (
    FEATURE_COLUMNS,
    ID_COLUMN,
    METRICS_PATH,
    MODEL_PATH,
    SHAP_VALUES_PATH,
    TEST_FEATURES_PATH,
    TEST_PREDICTIONS_PATH,
)
from explain import get_top_factors
from genai_advisor import generate_customer_explanation
from rag_assistant import answer_question, load_or_build_index

st.set_page_config(page_title="Churn Predictor & Retention Advisor", layout="wide")

CUSTOM_CSS = """
<style>
.block-container { padding-top: 2.2rem; max-width: 1180px; }
h1 { letter-spacing: -0.02em; }

.stat-row { display: flex; gap: 0.9rem; flex-wrap: wrap; margin: 1rem 0 1.6rem 0; }
.stat-card {
    flex: 1; min-width: 160px;
    background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px;
    padding: 0.85rem 1.1rem;
}
.stat-label { font-size: 0.72rem; font-weight: 600; color: #64748B; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.3rem; }
.stat-value { font-size: 1.4rem; font-weight: 700; color: #0F172A; }

.risk-badge { display: inline-block; padding: 0.28rem 0.8rem; border-radius: 999px; font-weight: 600; font-size: 0.8rem; margin-bottom: 0.55rem; }
.risk-critical { background: #FEE2E2; color: #B91C1C; }
.risk-high     { background: #FFEDD5; color: #C2410C; }
.risk-elevated { background: #FEF9C3; color: #A16207; }

.prob-value { font-size: 2.1rem; font-weight: 700; color: #0F172A; line-height: 1.1; }
.prob-track { background: #E2E8F0; border-radius: 999px; height: 9px; width: 100%; overflow: hidden; margin-top: 0.5rem; }
.prob-fill { height: 100%; border-radius: 999px; }

.mini-stat-row { display: flex; gap: 0.7rem; }
.mini-stat { flex: 1; background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 10px; padding: 0.65rem 0.9rem; }
.mini-label { font-size: 0.7rem; color: #64748B; text-transform: uppercase; letter-spacing: 0.04em; }
.mini-value { font-size: 1.15rem; font-weight: 700; color: #0F172A; margin-top: 0.15rem; }

.action-pill {
    display: inline-block; font-weight: 700; font-size: 0.9rem; color: #166534;
    background: #DCFCE7; border-radius: 8px; padding: 0.3rem 0.75rem; margin-bottom: 0.6rem;
}
.source-chip {
    display: inline-block; background: #EEF2FF; color: #4338CA; border-radius: 6px;
    padding: 0.18rem 0.6rem; font-size: 0.74rem; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    margin: 0.2rem 0.35rem 0.2rem 0;
}
</style>
"""


def _escape_markdown_dollars(text):
    """Escape literal '$' in LLM-generated text before handing it to
    Streamlit's markdown renderer.

    Gemini's answers often cite dollar figures (e.g. "$3,462,227 in
    revenue"). Streamlit renders markdown through MathJax, which treats a
    matched pair of unescaped '$' as inline LaTeX -- two dollar amounts in
    one sentence get silently parsed as a math expression instead of shown
    as text. Escaping to '\\$' keeps the literal dollar sign without
    triggering math mode.
    """
    return text.replace("$", r"\$") if text else text


def _risk_tier(prob):
    if prob >= 0.9:
        return "Critical risk", "risk-critical", "#DC2626"
    if prob >= 0.75:
        return "High risk", "risk-high", "#EA580C"
    return "Elevated risk", "risk-elevated", "#CA8A04"


@st.cache_resource
def load_artifacts():
    model_bundle = joblib.load(MODEL_PATH)
    shap_bundle = joblib.load(SHAP_VALUES_PATH)
    predictions = pd.read_csv(TEST_PREDICTIONS_PATH)
    test_features = pd.read_csv(TEST_FEATURES_PATH)
    return model_bundle, shap_bundle, predictions, test_features


@st.cache_resource
def load_metrics():
    with open(METRICS_PATH) as f:
        return json.load(f)


@st.cache_resource
def load_rag_index():
    # Cached per app process: building the index costs one Gemini API call
    # per corpus chunk (~12), which only needs to happen once whether it's
    # loaded from a locally pre-built models/rag_index.joblib or embedded
    # fresh on first use (e.g. a freshly deployed Streamlit Cloud app).
    return load_or_build_index()


def render_kpi_row(model_bundle, metrics, at_risk_count, total_count):
    st.markdown(
        f"""
        <div class="stat-row">
            <div class="stat-card"><div class="stat-label">Best model</div>
                <div class="stat-value">{html.escape(model_bundle['model_name'].replace('_', ' ').title())}</div></div>
            <div class="stat-card"><div class="stat-label">Test AUC-ROC</div>
                <div class="stat-value">{metrics['test_metrics']['test_roc_auc']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">Test F1</div>
                <div class="stat-value">{metrics['test_metrics']['test_f1']:.3f}</div></div>
            <div class="stat-card"><div class="stat-label">At risk (test set)</div>
                <div class="stat-value">{at_risk_count:,} / {total_count:,}</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_customer_explorer(model_bundle, shap_bundle, predictions, test_features):
    shap_df = shap_bundle["shap_values"]

    at_risk = predictions[predictions["y_pred"] == 1].sort_values("churn_probability", ascending=False)

    if at_risk.empty:
        st.warning("No customers were flagged as at-risk in the test set.")
        st.stop()

    options = [
        f"Customer {row.customer_id}  —  {row.churn_probability:.0%} churn probability"
        for row in at_risk.itertuples()
    ]
    id_lookup = dict(zip(options, at_risk["customer_id"]))

    selected_label = st.selectbox("Select an at-risk customer", options)
    customer_id = id_lookup[selected_label]

    customer_row = predictions[predictions[ID_COLUMN] == customer_id].iloc[0]
    feature_row = test_features[test_features[ID_COLUMN] == customer_id].iloc[0]
    prob = customer_row["churn_probability"]
    tier_label, tier_class, tier_color = _risk_tier(prob)

    col1, col2 = st.columns([1, 1.4])
    with col1:
        st.markdown(
            f"""
            <div class="risk-badge {tier_class}">{tier_label}</div>
            <div class="prob-value">{prob:.1%}</div>
            <div class="prob-track"><div class="prob-fill" style="width:{prob * 100:.1f}%; background:{tier_color};"></div></div>
            """,
            unsafe_allow_html=True,
        )
        st.caption("Predicted churn probability")
    with col2:
        st.markdown(
            f"""
            <div class="mini-stat-row">
                <div class="mini-stat"><div class="mini-label">Lifetime orders</div><div class="mini-value">{int(feature_row['frequency']):,}</div></div>
                <div class="mini-stat"><div class="mini-label">Lifetime value</div><div class="mini-value">${feature_row['monetary']:,.0f}</div></div>
                <div class="mini-stat"><div class="mini-label">Tenure</div><div class="mini-value">{int(feature_row['tenure_days']):,}d</div></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # test_features carries the exact feature vector explain.py computed
    # SHAP values against, so the chart shown here matches the model input.
    top_factors = get_top_factors(customer_id, shap_df, test_features[FEATURE_COLUMNS], test_features[ID_COLUMN], top_n=5)

    st.subheader("Top SHAP risk factors")
    st.caption(
        "How much each feature pushed this customer's predicted churn probability up or down, "
        "relative to the model's average prediction."
    )

    # top_factors is already sorted by |impact| descending (see
    # explain.get_top_factors); pin the chart's category order to that same
    # list rather than an in-chart "sort=-x" expression.
    chart_df = top_factors.copy()
    feature_order = chart_df["feature"].tolist()
    chart_df["direction_label"] = chart_df["direction"].map(
        {"increases churn risk": "Increases risk", "decreases churn risk": "Decreases risk"}
    )
    chart = (
        alt.Chart(chart_df)
        .mark_bar(cornerRadiusEnd=4)
        .encode(
            x=alt.X("shap_value:Q", title="Impact on churn probability"),
            y=alt.Y("feature:N", sort=feature_order, title=None, axis=alt.Axis(labelLimit=200)),
            color=alt.Color(
                "direction_label:N",
                title=None,
                scale=alt.Scale(domain=["Increases risk", "Decreases risk"], range=["#DC2626", "#16A34A"]),
                legend=alt.Legend(orient="top", title=None),
            ),
            tooltip=[
                alt.Tooltip("feature:N", title="Feature"),
                alt.Tooltip("value:Q", title="Customer value", format=",.1f"),
                alt.Tooltip("shap_value:Q", title="SHAP impact", format="+.3f"),
            ],
        )
    )
    st.altair_chart(chart, use_container_width=True)

    st.subheader("Gemini retention recommendation")
    if st.button("Generate explanation", type="primary"):
        with st.spinner("Calling Gemini..."):
            result = generate_customer_explanation(
                customer_id=customer_id,
                churn_probability=prob,
                top_factors=top_factors.to_dict("records"),
            )

        if result["needs_manual_review"]:
            with st.container(border=True):
                st.warning(f"Flagged for manual review: {result['error']}")
                if result["explanation"]:
                    st.caption("Model's explanation (unvalidated):")
                    st.write(_escape_markdown_dollars(result["explanation"]))
        else:
            # recommended_action is guaranteed to be an exact match from the
            # fixed ALLOWED_ACTIONS list (see genai_advisor.py's guardrail
            # check) whenever needs_manual_review is False, so it's safe to
            # place directly in this unsafe_allow_html block.
            with st.container(border=True):
                st.markdown(f'<div class="action-pill">{result["recommended_action"]}</div>', unsafe_allow_html=True)
                st.write(_escape_markdown_dollars(result["explanation"]))


EXAMPLE_QUESTIONS = [
    "Which customer segment has the highest churn risk and why?",
    "How much revenue is sitting with customers who have already churned?",
    "What did the RFM feature engineering exclude, and why?",
    "Which model performed best and by how much?",
]


def render_ask_the_analysis():
    st.caption(
        "Ask a free-form question about this project's own analysis. The assistant retrieves "
        "the most relevant snippets from the SQL results, model metrics, SHAP importances, and "
        "README findings, then answers using only those snippets -- see src/rag_assistant.py "
        "for the retrieval + guardrail design."
    )

    question = st.text_input("Your question", placeholder=EXAMPLE_QUESTIONS[0])
    st.caption("Examples: " + " · ".join(f"*{q}*" for q in EXAMPLE_QUESTIONS[1:]))

    if st.button("Ask", type="primary") and question.strip():
        with st.spinner("Retrieving context and calling Gemini..."):
            try:
                index = load_rag_index()
                result = answer_question(question, index=index)
            except Exception as exc:  # noqa: BLE001 - index build can fail without a valid key
                result = {"answer": None, "sources": [], "error": f"Could not build/load the RAG index: {exc}"}

        if result["error"]:
            st.warning(result["error"])
        else:
            with st.container(border=True):
                st.write(_escape_markdown_dollars(result["answer"]))
                if result["sources"]:
                    # Source keys come from our own indexed corpus (file
                    # names / chunk labels defined in rag_assistant.py), not
                    # from the model, but they're escaped anyway as cheap
                    # defense-in-depth before going into unsafe_allow_html.
                    chips = "".join(f'<span class="source-chip">{html.escape(s)}</span>' for s in result["sources"])
                    st.markdown(f'<div style="margin-top:0.5rem;">{chips}</div>', unsafe_allow_html=True)


def main():
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

    st.title("Intelligent Churn Predictor & Retention Advisor")
    st.caption(
        "Trained on the UCI Online Retail II dataset. Select an at-risk customer to see "
        "the statistical factors driving their churn score, then generate a plain-English "
        "explanation and a guarded retention recommendation with Gemini."
    )

    try:
        model_bundle, shap_bundle, predictions, test_features = load_artifacts()
        metrics = load_metrics()
    except FileNotFoundError:
        st.error(
            "Model artifacts not found. Run the pipeline first:\n\n"
            "`python src/data_prep.py && python src/train_model.py && python src/explain.py`"
        )
        st.stop()

    at_risk = predictions[predictions["y_pred"] == 1]
    render_kpi_row(model_bundle, metrics, len(at_risk), len(predictions))

    st.sidebar.header("About this project")
    st.sidebar.write(
        "An end-to-end churn prediction system: RFM-based churn labels, a "
        "leakage-checked model comparison, SHAP explainability, and a "
        "guardrailed Gemini retention advisor. See the README for the full "
        "methodology and business case."
    )
    st.sidebar.markdown("[Source on GitHub](https://github.com/Daton-Star/churn-predictor-retention-advisor)")

    tab1, tab2 = st.tabs(["Customer risk explorer", "Ask the analysis"])
    with tab1:
        render_customer_explorer(model_bundle, shap_bundle, predictions, test_features)
    with tab2:
        render_ask_the_analysis()


if __name__ == "__main__":
    main()
