"""Run every .sql file in this folder against online_retail.db and write
the real output to QUERY_RESULTS.md, so the queries' results are visible
in the repo without anyone needing a database client.

Run: `python sql/run_queries.py` (after `python sql/build_db.py`)
"""

import sqlite3
from pathlib import Path

SQL_DIR = Path(__file__).resolve().parent
DB_PATH = SQL_DIR / "online_retail.db"
OUTPUT_PATH = SQL_DIR / "QUERY_RESULTS.md"


def format_markdown_table(columns, rows):
    header = "| " + " | ".join(columns) + " |"
    separator = "|" + "|".join(["---"] * len(columns)) + "|"
    body = "\n".join("| " + " | ".join(str(v) for v in row) + " |" for row in rows)
    return "\n".join([header, separator, body])


def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    sql_files = sorted(SQL_DIR.glob("[0-9]*.sql"))
    sections = ["# SQL query results\n", "Generated by running each query in this folder against the real, cleaned dataset via `sql/run_queries.py`. Regenerate after `python sql/build_db.py`.\n"]

    for sql_file in sql_files:
        query = sql_file.read_text()
        cursor.execute(query)
        columns = [d[0] for d in cursor.description]
        rows = cursor.fetchall()

        sections.append(f"## `{sql_file.name}`\n")
        sections.append(f"```sql\n{query.strip()}\n```\n")
        sections.append(format_markdown_table(columns, rows) + "\n")
        print(f"{sql_file.name}: {len(rows)} rows")

    conn.close()
    OUTPUT_PATH.write_text("\n".join(sections))
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
